[package]
name = "belajar-axum"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["migration"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
futures = "0.3.30"
http-body = "1.0.0"
redis = "0.24.0"
sea-orm = { version = "0.12.14", features = ["runtime-tokio", "macros", "sqlx-postgres", "with-chrono", "with-uuid", "with-json"] }
serde = { version = "1.0.196", features = ["derive"] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.14"
tracing-subscriber = "0.3.18"
migration={path = "migration"}
dotenv = "0.15.0"
uuid = { version = "1.7.0", features = ["v4"] }

