version: "3"
services:
  string-team-api:
    build:
      context: .
      dockerfile: prod.Dockerfile
    environment:
        MODE: ${MODE}
        RUST_BACKTRACE: ${RUST_BACKTRACE}
        DATABASE_URL_DEV: ${DATABASE_URL_DEV}
        REDIS_URL_DEV: ${REDIS_URL_DEV}
        MINIO_URL_DEV: ${MINIO_URL_DEV}
        DATABASE_URL_PROD: ${DATABASE_URL_PROD}
        REDIS_URL_PROD: ${REDIS_URL_PROD}
        MINIO_URL_PROD: ${MINIO_URL_PROD}
        JWT_SECRET_DEV: ${JWT_SECRET_DEV}
        JWT_SECRET_PROD: ${JWT_SECRET_PROD}
        MINIO_ACCESS_KEY_DEV: ${MINIO_ACCESS_KEY_DEV}
        MINIO_SECRET_KEY_DEV: ${MINIO_SECRET_KEY_DEV}
        MINIO_ACCESS_KEY_PROD: ${MINIO_ACCESS_KEY_PROD}
        MINIO_SECRET_KEY_PROD: ${MINIO_SECRET_KEY_PROD}
        SMTP: ${SMTP}
    restart: always
    ports:
      - 5000
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`strong-team.id`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certResolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=5000"

networks:
  dokploy-network:
    external: true